DEVICE=S100
MANUFACTURE=lingyi

VENDOR_PATH=vendor/$MANUFACTURE/$DEVICE

LICENCES="\
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an \"AS IS\" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$MANUFACTURE/$DEVICE/setup-makefiles.sh
"

printf '%s' "$LICENCES" > $VENDOR_PATH/$DEVICE-vendor.mk
printf '
PRODUCT_COPY_FILES += \
' >> $VENDOR_PATH/$DEVICE-vendor.mk

end=`tail -n1 "proprietary-files.txt"`
for i in $(cat "proprietary-files.txt"); do
  printf "    %s:%s " "$VENDOR_PATH/proprietary/$i" "system/$i" >> $VENDOR_PATH/$DEVICE-vendor.mk
  if [ "$end" = "$i" ]; then break ;fi
  printf '\\\n' >> $VENDOR_PATH/$DEVICE-vendor.mk
done

printf '

PRODUCT_PACKAGES += \
    libaed \
    libaudiocustparam \
    libdpframework \
    libnvram \
    libpq_cust
' >> $VENDOR_PATH/$DEVICE-vendor.mk
